### ISSUE TITLE
Input component does not work with Angular CLI option

### ISSUE THREAD

**Issue by noradroid** [goetzrobin/spartan#197] opened 2024-03-08 03:18 UTC
### Please provide the environment you discovered this bug in.

Faced this issue in my Angular 17 workspace, no NX.

### Which area/package is the issue in?

input

### Description

Could not run the Angular CLI alternative (`ng g @spartan-ng/cli:ui input`) to use this component.

### Please provide the exception or error you saw

```true
$ ng g @spartan-ng/cli:ui input
[error] Error: Cannot find module 'nx/src/devkit-exports'
Require stack:
- C:\proj\node_modules\@nx\devkit\index.js
- C:\proj\node_modules\@spartan-ng\cli\src\generators\ui\compat.js
- C:\proj\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\proj\node_modules\@angular-devkit\schematics\tools\index.js
- C:\proj\node_modules\@angular\cli\src\command-builder\schematics-command-module.js
- C:\proj\node_modules\@angular\cli\src\commands\generate\cli.js
- C:\proj\node_modules\@angular\cli\src\commands\command-config.js
- C:\proj\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\proj\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\stray\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\proj\node_modules\@nx\devkit\index.js:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment] 2024-03-15 20:49
@noradroid i released a new version of the CLI please let me know if the issue is still occurring after upgrading

**Comment by goetzrobin** [comment] 2024-03-26 22:04
@noradroid I am closing this issue for now. Please reopen if the issue persists

**Closed by goetzrobin** 2024-03-26 22:04 UTC
Labels: bug
