### ISSUE TITLE
Why is the value of the select component wrapped in an array when the 'multiple' property is not present?

### ISSUE THREAD

**Issue by wizardnet972** [goetzrobin/spartan#188] opened 2024-03-04 07:14 UTC
### Please provide the environment you discovered this bug in.

Storybook and the code itself

### Which area/package is the issue in?

select

### Description

Why is the value of the select component wrapped in an array when it does not contain the `multiple` property?

<img width="890" alt="image" src="https://github.com/goetzrobin/spartan/assets/4997825/d6f124cc-af55-4bc7-ba9c-2dea28ea6b94">

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by thatsamsonkid** [comment] 2024-03-04 14:48
Hi, seems there is a few issues with the Select form compatibility that have been uncovered. I think both this issue and the other issue you raised #189 will be resolved with this PR #184

**Comment by wizardnet972** [comment] 2024-03-04 14:55
@thatsamsonkid Yes, I replaced those files and now the select has its initial value set as an object instead of an array. Could you please merge and publish this change?

**Comment by wizardnet972** [comment] 2024-03-04 15:57
@thatsamsonkid, there's another issue with the `select` functionality.

When I switch from having multiple selections to a single one in the `select` option, and then select a value, and then switch back to multiple selections, I find that I'm unable to select anything anymore.

Below is the code snippet that binds to the selects:

```typescript
  durations = {
    daily: [
      { label: 'Morning', value: 'morning' },
      { label: 'Afternoon', value: 'afternoon' },
    ],
    weekly: [
      { label: 'Monday', value: 'monday' },
      { label: 'Tuesday', value: 'tuesday' },
      { label: 'Wednesday', value: 'wednesday' },
      { label: 'Thursday', value: 'thursday' },
      { label: 'Friday', value: 'friday' },
    ],
    monthly: [
      { label: 'Start of Month', value: 'startOfMonth' },
      { label: 'End of Month', value: 'endOfMonth' },
    ],
    quarterly: [
      { label: 'Start of Quarter', value: 'startOfQuarter' },
      { label: 'End of Quarter', value: 'endOfQuarter' },
    ],
  };
  frequencies = Object.keys(this.durations).map((k) => ({ label: upperFirst(k), value: k.toLowerCase() }));

  reports = [{ name: 'Clients', frequency: null, duration: null, active: true }];
```

The `frequencies` select influences the `duration` select. When the `frequencies` select has the value of `daily`, the `duration` select transforms into a multiselect.

Here's the scenario:
1. Select `daily` in the `frequencies` select.
2. Choose two values in the `duration` select.
3. Change to `weekly` in the `frequencies` select.
4. Pick one value in the `duration` select.
5. Switch back to `daily` in the `frequencies` select.
6. Attempt to select values in the `duration` select (unable to).

The `frequencies` select:

```html
   <hlm-select class="inline-block" [(ngModel)]="report.frequency" placeholder="Select frequency">
                    <hlm-select-trigger class="w-56">
                      <hlm-select-value />
                    </hlm-select-trigger>
                    <hlm-select-content class="w-56">
                      <hlm-option *ngFor="let frequency of frequencies" [value]="frequency.value">{{ frequency.label }}</hlm-option>
                    </hlm-select-content>
                  </hlm-select>
```

The duration select:

```html
                  <hlm-select
                    class="inline-block"
                    placeholder="Select time/duration"
                    [multiple]="report.frequency === 'daily'"
                    [(ngModel)]="report.duration">
                    <hlm-select-trigger class="w-56">
                      <hlm-select-value />
                    </hlm-select-trigger>
                    <hlm-select-content class="w-56">
                      <hlm-option *ngFor="let duration of durations[report.frequency]" [value]="duration.value">
                        {{ duration.label }}
                      </hlm-option>
                    </hlm-select-content>
                  </hlm-select>
```

**Comment by wizardnet972** [comment] 2024-03-05 12:13
@thatsamsonkid and @goetzrobin, I'm currently investigating the source code of the select and Angular CDK. It appears that you're utilizing [listbox](https://github.com/angular/components/blob/main/src/cdk/listbox/listbox.ts#L363) to retrieve all the checked items. However, it seems that this approach isn't functioning as expected in the mainion scenario. Specifically, when it transitions to 'multiple' mode, the listbox retains values even when they are unchecked.

Therefore, I propose a straightforward solution: upon a mode change (such as transitioning to 'multiple'), clear all selected items as follows:

```typescript
_cdkListbox.selectionModel.selected.forEach(value => {
   _cdkListbox.selectionModel.deselect(value)
});
```

It appears that Angular/CDK doesn't effectively clear the items in such scenarios.

**Comment by thatsamsonkid** [comment] 2024-03-05 13:07
So I think that was intentional by the material team. They only clear if you go from multiple -> single because there's no way to know which option to keep if multiple are selected. 

If you go from single to multiple there is no issue there since your just allowing to add additional options. I think from a default behavior I think this is fine, but I do believe if you have a use case where it does need to be cleared then since I assume you are programmatically changing the mode anyways then you can also just clear the form field through your form control I believe as well.

That PR is still being finalized, its also not might PR, i'm just a reviewer for that one but we are definitely determined to get these fixes in as soon as possible!

**Comment by wizardnet972** [comment] 2024-03-05 17:17
@thatsamsonkid

I've demonstrated the issue here, and it's not tied to the `form` model. In the provided example, there's no form model involved.

https://stackblitz.com/edit/github-s5zire?file=src%2Fmain.ts

1. Begin by selecting "Weekly" for the frequency, then choose "Monday" for the duration.
2. Next, switch the frequency to "Daily" and select "Morning" for the duration. You'll observe that this selection doesn't function as expected.

I've reproduced the issue using select source files and implemented changes from the https://github.com/goetzrobin/spartan/pull/184 PR by substituting the brain source code with three modifications from the PR.

**Comment by jon9090** [comment] 2024-03-05 20:21
+1. 
The issue is identical for me.

**Comment by thatsamsonkid** [comment] 2024-03-08 07:39
Hmm ok thanks for putting that example together. Maybe what we could do is add an input/flag "clearOnModeChange" to enforce clearing regardless of what mode is transitioning to. Im a little hesitant to make it the default behavior. I believe the intention behind that default behavior is to be the least destructive to data where possible. @goetzrobin @elite-benni any thoughts on this one?

**Comment by elite-benni** [comment] 2024-03-08 21:00
> Hmm ok thanks for putting that example together. Maybe what we could do is add an input/flag "clearOnModeChange" to enforce clearing regardless of what mode is transitioning to. Im a little hesitant to make it the default behavior. I believe the intention behind that default behavior is to be the least destructive to data where possible. @goetzrobin @elite-benni any thoughts on this one?

I totally understand both points. 
In the example all options also changed, and I can understand that in this case the value should just be cleared, even if it is a change from single to multiple. 
But if the options stay the same, and there is only one selected, it should remain selected.

**Closed** 2024-03-18 18:34 UTC
Labels: bug
